### ISSUE TITLE
WARNING in E:\Imover\src\app\app.module.ts depends on 'ng-event-bus'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### ISSUE THREAD

**Issue by UTSOURCE** [cristiammercado/ng-event-bus#10]
WARNING in E:\Imover\src\app\app.module.ts depends on 'ng-event-bus'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by HimanshuGoel** [comment]
We are also facing the same warning after Angular 10 upgrade. Like this chart.js issue, a similar package needs to be released for ng-event-bus to support ES Module.
https://github.com/chartjs/Chart.js/issues/7550

**Comment by cristiammercado** [comment]
Hi,

I'm already working on this issue, in the next few days I will be releasing a new version to solve this.

**Comment by UTSOURCE** [comment]
@cristiammercado Has it been resolved, not released yet

**Comment by cristiammercado** [comment]
Hi,

This warning has been fixed in [v2.0.0](https://github.com/cristiammercado/ng-event-bus/releases/tag/v2.0.0) published in [npm](https://www.npmjs.com/package/ng-event-bus/v/2.0.0). This version contains breaking changes, please check releases page for more info.
