### ISSUE TITLE
Suggestion: Include Event Bus Key on Callback

### ISSUE THREAD

**Issue by pvillaverde** [cristiammercado/ng-event-bus#7]
Greetings!

Thanks for this amazing plugin! I was migrating from AngularJS to Angular 9 and was looking for something like this. The only thing I missed so far is the posibility to have and use the event bus key on the callback function. 

So for example I have a page where I listen for updates on 2 resources in order to update a badge. And those resources may emit a increase or decrease event. I think it would be better to handle the different logic for increase or decrease bassed on the bus of each event, instead of having multiple listeners, one for each event. This could be done if the suscribe callback could come with an additional parameter with the event bus key.

Thanks in advance and please correct me if I'm wrong or there are better ways to do it (Or it's already implemented and I didn't see it).

**Comment by cristiammercado** [comment]
Hi @pvillaverde ,

There's not something implemented for what you comment, but if you maybe give me an example similar to what you want to achieve, I could include it in a next version.

Sorry for the delay in the response!

**Comment by pvillaverde** [comment]
Hey there!

No worries at all. What I mean is to return an object, for example
```js
{
     key: 'notifications:created'  //The key string of the event bus
     data:  {notificationItem}  // (current Message)
}
```
So for example on some cases where you want to know if an item was created,deleted or updated you can make only 1 subscription (`notifications:*`)  and handle in the callback depending on the action(created,deleted, etc..), something like the old postalJS do with the envelope https://github.com/postaljs/postal.js/blob/master/README.md

Thanks for the answer! :-)

**Comment by cristiammercado** [comment]
@pvillaverde I like your idea. I'm going to make the returned observable receive a second optional parameter with the message metadata, including original cast key and timestamp. Maybe something like this to avoid a breaking change and launch the feature in a minor change in the next release:

```js
eventBus.on('app:start').subscribe((message, metadata) => {
    console.log('Message:', message);
    console.log('Metadata:', metadata);
});
```

**Comment by flipdoubt** [comment]
I agree this is especially helpful when using wildcards, but I worked around this by manually included the key in the data passed into the callback, as the OP does in the example.

**Comment by pvillaverde** [comment]
Yes, that's the same workarround I used, but it break the rule of dont repeat yourself.. If in the future it can be implemented on the library itself, it would be a much better aproach!

**Comment by cristiammercado** [comment]
Hi,

This functionality has been added in [v2.0.0](https://github.com/cristiammercado/ng-event-bus/releases/tag/v2.0.0) published in [npm](https://www.npmjs.com/package/ng-event-bus/v/2.0.0).
